Revert "[FEATURE] Improve usability for BE database thumbnails/file icons"
This reverts commit bedddf2e0fb50b0ebe3751f8563ee8021c945303

Reason for reverting the mentioned commit:
Fatal error: Call to undefined method
TYPO3\CMS\Core\Resource\File::getAlternative()
    
Related: #47709
Releases: 6.2

Change-Id: Ie0ed98b2315bedf4475d25e92a3842972e85b7bf
Reviewed-on: https://review.typo3.org/24809
Reviewed-by: Oliver Hader
Tested-by: Oliver Hader