[TASK] Update CKEditor to 4.7.2
Update CKEditor to the lastest version that fixes a lot of bugs.

Release notes:
https://ckeditor.com/release-notes

Fixes:
 * Added Advanced Content Filter integration with the Justify plugin.
 * [Chrome] Fixed: Clicking the scrollbar throws an Uncaught TypeError:
 element.is is not a functionerror.
 * Fixed: Widgets cannot be properly pasted into a table cell.
 * Fixed: Internal cke_table-faked-selection-table class is visible
 in the Stylesheet Classes field of the Table Properties dialog.
 * [Edge] Fixed: Error thrown when pressing the Select All button
 in Source Mode.
 * Fixed: Double slash in the path to stylesheet needed by the
 Table Selection plugin.
 * Fixed: Unnecessary dependency on the Editor Toolbar plugin inside
 the Notification plugin.
 * Fixed: Error thrown into the browser console after opening the
 Styles Combo plugin menu in the editor without any selection.
 * Fixed: Double click does not open the dialog for modifying anchors
 inserted via the Link plugin.
 * [IE8-9] Fixed: Clicking inside an empty read-only editor throws
 an error.
 * [IE10] Fixed: Clicking below a single horizontal rule throws
 an error.
 * Fixed: The range.cloneContents method selects the whole element when
 the selection starts at the beginning of that element.
 * Fixed: The range.extractContents method returns an incorrect result
 when multiple nodes are selected.
 * Fixed: The elementPath.contains method incorrectly excludes the last
 element instead of root when the fromTop parameter is set to true.
 * Fixed: SCAYT leaves underlined word after the CKEditor Replace
 dialog corrects it.
 * Added the CKEDITOR.dom.nodeList.toArray method which returns an
 array representation of a node list.

Resolves: #82143
Releases: master, 8.7
Change-Id: I6f6037e48d768e4a2887c799c1791f3201ce40c8
Reviewed-on: https://review.typo3.org/53751
Reviewed-by: Andreas Fernandez <typo3@scripting-base.de>
Tested-by: Andreas Fernandez <typo3@scripting-base.de>
Tested-by: TYPO3com <no-reply@typo3.com>
Reviewed-by: Kasper Ligaard <kasperligaard+typo3.org@gmail.com>
Tested-by: Kasper Ligaard <kasperligaard+typo3.org@gmail.com>
Reviewed-by: Georg Ringer <georg.ringer@gmail.com>
Tested-by: Georg Ringer <georg.ringer@gmail.com>
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: Benni Mack <benni@typo3.org>