[BUGFIX] Fix JS errors in configuration wizard of backend layout
Loading of the ExtJS stuff was missing.

And also do some cleanup stuff
(getLanguageService, getDatabaseConnection).

Add fix for another JavaScript error
 TypeError: top.TYPO3.settings.ContextHelp is undefined

Resolves: #66120
Releases: master
Change-Id: I32f1b2e170267c250f296b2bb27ea3c48095cb68
Reviewed-on: http://review.typo3.org/38336
Reviewed-by: Markus Klein <klein.t3@reelworx.at>
Tested-by: Markus Klein <klein.t3@reelworx.at>
Reviewed-by: Mathias Schreiber <mathias.schreiber@wmdb.de>
Tested-by: Mathias Schreiber <mathias.schreiber@wmdb.de>
Reviewed-by: Wouter Wolters <typo3@wouterwolters.nl>
Tested-by: Wouter Wolters <typo3@wouterwolters.nl>