[BUGFIX] Cannot redeclare class bigDoc: move_el.php
The file move_el.php first requires init.php
and then template.php. As template.php was
already required by the autoloader during
initialization process this results in a
fatal error: Cannot redeclare...

The patch removes the require statement for
template.php

Change-Id: I096ecfb017f5ec78ac1be35d3bcd985d88b82a56
Fixes: #38763
Releases: 6.0
Reviewed-on: http://review.typo3.org/12712
Reviewed-by: Steffen Ritter
Reviewed-by: Helmut Hummel
Tested-by: Helmut Hummel