[BUGFIX] Ensure proper identifier quoting in AbstractMenuContentObject
PostgresSQL seems to get picky with upper case column names, if
they are not proper quoted in queries, like `pages.SYS_LASTCHANGED`
as example. Executing such database queries will return database
error message like

 ERROR:  column "sys_lastchanged" does not exist

also it has been provided as upper case variant. Related to system
architecture and historical build up sometimes sql parts are build
manually instead of using QueryBuilder directly. Thus fields and
values are eventually not properly quoted, thus leading to this
error message.

This can be verified using ext:styleguide frontend pages and open
the `/menu-recently-updated` using postgres dbms backend.

This change ensures proper quoting for build up of the extraWhere
(or additionalWhere) in core content object class
`\TYPO3\CMS\Frontend\ContentObject\Menu\AbstractMenuContentObject`.

Resolves: #98561
Releases: main, 11.5
Change-Id: I28541eafd1ceee360c78b54d24967286ec66ea9a
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/76035
Tested-by: core-ci <typo3@b13.com>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>