[TASK] Ensure removing dangling images works with podman
The TYPO3 core `runTests.sh` contains the `-u` option to
update the images and remove dangling images. Providing
an image name and a `--filter` option is not supported
by podman:
 > Error: cannot specify an image and a filter(s)
 and has not been discovered yet in the TYPO3
core implementation yet.

Both container runtimes `docker` and `podman` support filtering images
using the `reference` filter option. Therefore, this change modifies
the dangling image removal to use multiple filters

To verify that filtering with two `--filter` options can be used with
podman and docker, the following commands can be executed to list the
set of local non-dangling images.

Note: This example uses `dangling=false` instead of
	  `dangling=true` (as in `runTests.sh`), since we expect
      most developers don't have dangling images yet.

> podman images \
    --filter "reference=ghcr.io/typo3/core-testing-*" \
    --filter "dangling=false" --format "{{.ID}}"

> docker images \
    --filter "reference=ghcr.io/typo3/core-testing-*" \
    --filter "dangling=false" --format "{{.ID}}"

Resolves: #102697
Releases: main, 12.4, 11.5
Change-Id: I717d1aa229bdfb73c63aa5b2d46e1aff665544cb
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/82236
Tested-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>